# UI constants (moved from view modules)
PADDING = 10
HEADER_HEIGHT = 40
CIRCLE_RADIUS = 16
HEADER_FONT_SIZE = 26
HEADER_SMALL_FONT_SIZE = 24

MAIN_BOTTOM_PADDING = 35
START_X_OFFSET = 40
END_X_OFFSET = 40
LINE_Y_OFFSET = 60
TRAIN_ICON_BASE_OFFSET = 8

TIME_BIG_FONT_SIZE = 82
TIME_MIN_FONT_SIZE = 28
TIME_LEFT_PADDING = 10
TIME_BOTTOM_OFFSET = 105
TIME_SECONDARY_X = 200

FOOTER_BAR_HEIGHT = 15

# Screen dimensions
SCREEN_WIDTH = 400
SCREEN_HEIGHT = 300

# Font paths
FONT_PATH_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"